# Site settings
title: Alf.io, the open source ticket reservation system
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A powerful reservation system. Keep control of your event and keep attendees data away from big players.
  Don't annoy them with additional fees, pay only what is really needed!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alf.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
